// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetWorthTracker.Database;

#nullable disable

namespace NetWorthTracker.Database.Migrations
{
    [DbContext(typeof(NetWorthTrackerDbContext))]
    [Migration("20260123172922_DefinitionsOneTable")]
    partial class DefinitionsOneTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("NetWorthTracker.Database.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("EntryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entry_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("NetWorthTracker.Database.Models.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("EntryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entry_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("debts", (string)null);
                });

            modelBuilder.Entity("NetWorthTracker.Database.Models.Definition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("definitions", (string)null);
                });

            modelBuilder.Entity("NetWorthTracker.Database.Models.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("entries", (string)null);
                });

            modelBuilder.Entity("NetWorthTracker.Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NetWorthTracker.Database.Models.Asset", b =>
                {
                    b.HasOne("NetWorthTracker.Database.Models.Entry", "Entry")
                        .WithMany("Assets")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("NetWorthTracker.Database.Models.Debt", b =>
                {
                    b.HasOne("NetWorthTracker.Database.Models.Entry", "Entry")
                        .WithMany("Debts")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("NetWorthTracker.Database.Models.Definition", b =>
                {
                    b.HasOne("NetWorthTracker.Database.Models.User", "User")
                        .WithMany("Definitions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetWorthTracker.Database.Models.Entry", b =>
                {
                    b.HasOne("NetWorthTracker.Database.Models.User", "User")
                        .WithMany("Entries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetWorthTracker.Database.Models.Entry", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Debts");
                });

            modelBuilder.Entity("NetWorthTracker.Database.Models.User", b =>
                {
                    b.Navigation("Definitions");

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
