<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.18" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\NetWorthTracker.Application\NetWorthTracker.Application.csproj" />
      <ProjectReference Include="..\NetWorthTracker.Infrastructure\NetWorthTracker.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Remove="appsettings.secrets.*.json" />
        <Content Include="appsettings.secrets.*.json" Exclude="appsettings.secrets.*.enc.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </Content>
    </ItemGroup>

    <PropertyGroup>
        <WarningsAsErrors>
            CS8981; <!--> Type name 'foo' consists only of lowercase letters <-->
            SA1300; <!-->  Element 'foo' should begin with an uppercase letter <-->
            SA1649 <!--> File name should match first type name <-->
        </WarningsAsErrors>
    </PropertyGroup>

</Project>
